apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: postgre_trace
spec:
  type: bindings.postgres
  version: v1
  metadata:
  - name: url
    value: postgresql://saas_test:saas_pass@saas-db:5432
