apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: saas-log
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis_state:6379
  - name: redisPassword
    secretKeyRef:
      name: redis
      key: ""
